version: 0.3

chains:
  build:
    matrix:
      - - env:
            RELEASE: ""
        - env:
            RELEASE: "--release"
    tasks:
      - script: |
          set -e
          cargo build $FEATURES $RELEASE

  test:
    tasks:
      - script: |
          set -e
          cargo test

  "hook:pre-push":
    pre:
      - build
      - test
    tasks: []
